#version 430 core

layout(local_size_x = 8, local_size_y = 4) in;

layout(rgba32f, binding = 0) uniform image2D o_framebufferTex;

// Data we write to that is used in later passes
layout(rgba32f, binding = 1) uniform image2D hitLocations;
layout(rgba32f, binding = 2) uniform image2D triangleNormals;
layout(rgba32f, binding = 3) uniform image2D texMatInfo;

layout(r32f, binding = 4) uniform image2D shadowBuffer;

struct Triangle
{
    // Vertex positions
    vec3 a;
    vec3 b;
    vec3 c;
    vec3 normal;

    // UV Coordinates for each vertex
    vec2 uvA;
    vec2 uvB;
    vec2 uvC;

    int textureIndex;
    int materialIndex;
};

layout(std430, binding = 5) readonly buffer b_trianglesSSBO
{
    Triangle sceneTris[];
};

struct Node
{
    // Laid out like this for bit packing
    vec3 minBound;

    // Holds index of left node (if not leaf node) or first triangle (if leaf node)
    int leftFirst;
    vec3 maxBound;

    // Triangles in node (0 if not leaf node)
    int triangleCount;
};

layout(std430, binding = 6) readonly buffer b_bvhNodes
{
    Node bvhNodes[];
};

// Maps bvhNode.leftFirst indexes to indexes in sceneTris
layout(std430, binding = 7) readonly buffer b_bvhTriangleIndex
{
    int bvhTriIdxs[];
};

struct Camera { vec3 position; vec3 forward; vec3 right; vec3 up; };
uniform Camera u_camera;

#define MAX_LIGHTS 10
struct Light
{
    vec3 points[4];
    vec3 color;
    float intensity;
    float radius;
};

uniform Light u_lights[MAX_LIGHTS];
uniform int u_numLights;

uniform vec2 u_resolution;

struct Ray  { vec3 origin; vec3 direction; };

struct RaycastResult {
    bool hit;
    float distance;
    vec3 position;
    vec3 normal;
    int triangleIndex;
};

const float PI = 3.14159265359;

// A "random" function I found in a stack overflow comment section
// Basically, the pattern between sequential values is too much to make
// to a person, so it may aswell be random
uint pcg_hash(uint seed)
{
  uint state = seed * 747796405u + 2891336453u;
  uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
  return (word >> 22u) ^ word;
}

// Used to advance the PCG state.
uint rand_pcg(inout uint rng_state)
{
  uint state = rng_state;
  rng_state = rng_state * 747796405u + 2891336453u;
  uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
  return (word >> 22u) ^ word;
}

// Advances the prng state and returns the corresponding random float.
float rand(uint state)
{
  uint x = rand_pcg(state);
  state = x;
  return float(x)*uintBitsToFloat(0x2f800000u);
}

// Calculate barycentric coordinates of _result.position
// Converts point on triangle to l_pixelCoords coordinate for texture)
vec2 CalculateTexUVs(RaycastResult _result, Triangle _tri)
{
    vec3 l_edgeAB = _tri.b - _tri.a;
    vec3 l_edgeAC = _tri.c - _tri.a;
    vec3 l_edgeAP = _result.position - _tri.a;

    // Calculate cross products for barycentric coordinates
    vec3 l_PcrossAB = cross(l_edgeAP, l_edgeAB);
    vec3 l_PcrossAC = cross(l_edgeAP, l_edgeAC);
    
    // Total triangle area is twice the actual area, because the triangle is 3D and has 2 sides
    float l_invTotalTriangleArea = 1.0f /  length(cross(l_edgeAB, l_edgeAC));
    
    // Calculate area of 3 sceneTris inside ABC, each made of 2 vertices and the intersection point
    float l_areaPCA = length(l_PcrossAC) * l_invTotalTriangleArea;
    float l_areaPAB = length(l_PcrossAB) * l_invTotalTriangleArea;

    // Total area of the system = 1, so we can cheat the last one
    float l_areaPBC = 1.0 - l_areaPCA - l_areaPAB;
    
    // The UV coordinate at P is the sum of the l_pixelCoords coordinates at each vertex,
    // each weighted by an area of a triangle consisting of the other 3 points.
    // The system has the Triangle edges (A, B, C) and the point of interest (P)
    vec2 interpolatedUV = _tri.uvA * l_areaPBC + 
                          _tri.uvB * l_areaPCA + 
                          _tri.uvC * l_areaPAB;
    
    return interpolatedUV;
}

RaycastResult TriangleIntersect(Ray _ray, Triangle _tri, int _index)
{
    RaycastResult result;
    result.hit = false;
    result.triangleIndex = _index;

    float l_ep = 0.0001;

    vec3 edge1 = _tri.b - _tri.a;
    vec3 edge2 = _tri.c - _tri.a;
    vec3 s = _ray.origin - _tri.a;
    
    vec3 ray_cross_edge2 = cross(_ray.direction, edge2);
    float det = dot(edge1, ray_cross_edge2);

    if(det > -l_ep && det < l_ep)
    {
        return result;
    }

    float inv_det = 1.0 / det;
    float u = inv_det * dot(s, ray_cross_edge2);

    if(u < 0.0 || u > 1.0)
    {
        return result;
    }

    vec3 s_cross_e1 = cross(s, edge1);
    float v = inv_det * dot(_ray.direction, s_cross_e1);

    if(v < 0.0 || u + v > 1.0)
    {
        return result;
    }

    float t = inv_det * dot(edge2, s_cross_e1);

    if(t > l_ep)
    {
        result.hit = true;
        result.position = _ray.origin + _ray.direction * t;
        result.distance = t;
        result.normal = _tri.normal;
        return result;
    }

    return result;
}

bool IntersectAABB(inout Ray _ray, vec3 _minBound, vec3 _maxBound)
{
    float tmin = 0.0f;
    float tmax = 10000000.0f;

    for (int i = 0; i < 3; i++)
    {
        if (abs(_ray.direction[i]) < 0.0001f)
        {
            if (_ray.origin[i] < _minBound[i] || _ray.origin[i] > _maxBound[i])
                return false;
        }
        else
        {
            float ood = 1.0f / _ray.direction[i];
            float t1 = (_minBound[i] - _ray.origin[i]) * ood;
            float t2 = (_maxBound[i] - _ray.origin[i]) * ood;

            if (t1 > t2)
            {
                float temp = t1;
                t1 = t2;
                t2 = temp;
            }

            tmin = max(tmin, t1);
            tmax = min(tmax, t2);

            if (tmin > tmax)
            {
                return false;
            }
        }
    }

    return true;
}

RaycastResult TraverseBVH(inout RaycastResult _result, inout Ray _ray)
{
    int l_indexStack[64];
    int l_top = 0;
    l_indexStack[l_top] = 0;

    Node l_node = bvhNodes[l_indexStack[l_top]];
    l_top++;

    do
    {
        if(IntersectAABB(_ray, l_node.minBound, l_node.maxBound))
        {
            if(l_node.triangleCount > 0)
            {
                for(int i = 0; i < l_node.triangleCount; i++)
                {
                    RaycastResult newResult = TriangleIntersect(_ray, sceneTris[bvhTriIdxs[l_node.leftFirst + i]], bvhTriIdxs[l_node.leftFirst + i]);
                    if(newResult.hit && newResult.distance < _result.distance)
                    {
                        _result = newResult;
                    }
                }
            }
            else
            {
                l_indexStack[l_top] = l_node.leftFirst;
                l_top++;
                l_indexStack[l_top] = l_node.leftFirst + 1;
                l_top++;
            }
        }

        l_top--;
        l_node = bvhNodes[l_indexStack[l_top]];
    } while(l_top > -1);

    return _result;
}

void main()
{
    ivec2 l_pixelCoords = ivec2(gl_GlobalInvocationID.xy);

    vec2 l_normalizedScreenCoords = vec2(((float(l_pixelCoords.x) / u_resolution.x) - 0.5) * 2.0,
                                         ((float(l_pixelCoords.y) / u_resolution.y) - 0.5) * 2.0);

    // Calculate aspect ratio
    float aspect = u_resolution.x / u_resolution.y;

    vec3 l_rayDir = normalize(u_camera.forward + 
                           l_normalizedScreenCoords.x * u_camera.right * aspect + 
                           l_normalizedScreenCoords.y * u_camera.up);
    
    Ray l_ray;
    l_ray.origin = u_camera.position;
    l_ray.direction = l_rayDir;

    // Return structure with hit information (if hit)
    RaycastResult l_closestHit;
    l_closestHit.hit = false;
    l_closestHit.distance = 1e10;
    l_closestHit.normal = vec3(0.0);
    
    TraverseBVH(l_closestHit, l_ray);

    if(l_closestHit.hit)
    {
        Triangle l_tri = sceneTris[l_closestHit.triangleIndex];

        // if(dot(l_closestHit.normal, l_ray.direction) > 0.0)
        // {
        //     l_closestHit.normal = -l_closestHit.normal;
        // }

        imageStore(hitLocations, l_pixelCoords, vec4(l_closestHit.position, l_closestHit.distance));
        imageStore(triangleNormals, l_pixelCoords, vec4(l_closestHit.normal, l_closestHit.triangleIndex));
        
        vec2 l_texUVs = CalculateTexUVs(l_closestHit, l_tri);
        imageStore(texMatInfo, l_pixelCoords, vec4(l_texUVs, float(l_tri.textureIndex), float(l_tri.materialIndex)));

        // DEBUG: output greyscale to framebuffer
        imageStore(o_framebufferTex, l_pixelCoords, vec4(vec3(200.0f - (l_closestHit.distance * 20)), 1.0f));
        // imageStore(o_framebufferTex, l_pixelCoords, vec4(normalize(l_closestHit.position), 1.0f));
        // imageStore(o_framebufferTex, l_pixelCoords, vec4(l_texUVs, 0.0f, 1.0f));
        // imageStore(o_framebufferTex, l_pixelCoords, vec4(u_lights[0].color, 1.0f));
    }
    else
    {
        imageStore(hitLocations, l_pixelCoords, vec4(0.0f));
        imageStore(triangleNormals, l_pixelCoords, vec4(0.0f));
        imageStore(texMatInfo, l_pixelCoords, vec4(0.0f));


        imageStore(o_framebufferTex, l_pixelCoords, vec4(vec3(0.0f), 1.0f));
    }
}