#version 430 core

layout(local_size_x = 8, local_size_y = 4) in;

layout(rgba32f, binding = 0) uniform image2D o_framebufferTex;

layout(rgba32f, binding = 1) uniform image2D intersectPositions;
layout(rgba32f, binding = 2) uniform image2D triangleNormals;
layout(rgba32f, binding = 3) uniform image2D uvCoordinatesAndTexIdx;
layout(rgba32f, binding = 4) uniform image2D matAlbedo;
layout(rgba32f, binding = 5) uniform image2D matProperties;
layout(r32f, binding = 6) uniform image2D shadowBuffer;

#define MAX_TEXTURES 10
layout(binding = 11) uniform sampler2D u_materialTextures[MAX_TEXTURES];

struct Camera { vec3 position; vec3 forward; vec3 right; vec3 up; };
uniform Camera u_camera;

struct Light{ vec3 color; vec3 position; };
#define MAX_LIGHTS 10
uniform Light u_lights[MAX_LIGHTS];
uniform int u_numLights;

uniform vec2 u_resolution;

const float PI = 3.14159265359;
// ----------------------------------------------------------------------------
float DistributionGGX(vec3 N, vec3 H, float roughness)
{
    float a = roughness*roughness;
    float a2 = a*a;
    float NdotH = max(dot(N, H), 0.0);
    float NdotH2 = NdotH*NdotH;

    float nom   = a2;
    float denom = (NdotH2 * (a2 - 1.0) + 1.0);
    denom = PI * denom * denom;

    return nom / denom;
}
// ----------------------------------------------------------------------------
float GeometrySchlickGGX(float NdotV, float roughness)
{
    float r = (roughness + 1.0);
    float k = (r*r) / 8.0;

    float nom   = NdotV;
    float denom = NdotV * (1.0 - k) + k;

    return nom / denom;
}
// ----------------------------------------------------------------------------
float GeometrySmith(vec3 N, vec3 V, vec3 L, float roughness)
{
    float NdotV = max(dot(N, V), 0.0);
    float NdotL = max(dot(N, L), 0.0);
    float ggx2 = GeometrySchlickGGX(NdotV, roughness);
    float ggx1 = GeometrySchlickGGX(NdotL, roughness);

    return ggx1 * ggx2;
}
// ----------------------------------------------------------------------------
vec3 fresnelSchlick(float cosTheta, vec3 F0)
{
    return F0 + (1.0 - F0) * pow(clamp(1.0 - cosTheta, 0.0, 1.0), 5.0);
}
// ----------------------------------------------------------------------------

void main()
{
    ivec2 l_pixelCoords = ivec2(gl_GlobalInvocationID.xy);
    vec3 l_position = imageLoad(intersectPositions, l_pixelCoords).xyz;
    vec2 l_texUVs = imageLoad(uvCoordinatesAndTexIdx, l_pixelCoords).xy;

    if(length(l_position) == 0.0f)
    {
        imageStore(o_framebufferTex, l_pixelCoords, vec4(0.0, 0.1, 0.3, 1.0));
        return;
    }

    if(imageLoad(shadowBuffer, l_pixelCoords).r == 0.0)
    {
        imageStore(o_framebufferTex, l_pixelCoords, vec4(0.0));
        return;
    }

    int l_texId = int(imageLoad(uvCoordinatesAndTexIdx, l_pixelCoords).z);
    
    vec3 l_objectColor = texture(u_materialTextures[l_texId], l_texUVs).rgb;
    vec3 l_aldebo = imageLoad(matAlbedo, l_pixelCoords).xyz;
    vec3 l_matProps = imageLoad(matProperties, l_pixelCoords).rgb;

    // Flip normal if it's facing away from the ray (backface)
    vec3 l_normal = normalize(imageLoad(triangleNormals, l_pixelCoords).rgb);
    vec3 V = normalize(u_camera.position - l_position);

    vec3 F0 = mix(vec3(0.04), l_aldebo, l_matProps[0]);
    vec3 Lo = vec3(0.0f);
    for(int i = 0; i < u_numLights; i++)
    {   
        vec3 l_lightDir = normalize(u_lights[i].position - l_position);
        vec3 l_halfLength = normalize(V + l_lightDir);
        float l_distance = length(u_lights[i].position - l_position);
        float l_attenuation = 1.0 / (l_distance * l_distance);
        vec3 l_radiance = u_lights[i].color * l_attenuation;

        // Cook-Torrance BRDF
        float NDF = DistributionGGX(l_normal, l_halfLength, l_matProps[1]);
        float G = GeometrySmith(l_normal, V, l_lightDir, l_matProps[1]);
        vec3 F = fresnelSchlick(clamp(dot(l_halfLength, V), 0.0, 1.0), F0);

        vec3 l_numerator = NDF * G * F;

        float NdotL = max(dot(l_normal, l_lightDir), 0.0);
        float l_denom = 4.0 * max(dot(l_normal, V), 0.0) * NdotL + 0.001;
        vec3 l_specular = l_numerator / l_denom;

        vec3 kS = F;

        vec3 kD = vec3(1.0) - kS;

        kD *= 1.0 - l_matProps[0];

        Lo += ((kD * l_aldebo * l_objectColor) / PI + l_specular) * l_radiance * NdotL;
    };
    
    // Add ambient lighting (always present, even in shadows)
    vec3 l_ambient = vec3(0.03) * l_objectColor * l_aldebo * l_matProps[2];
    
    vec3 colour = l_ambient + Lo;
    
    imageStore(o_framebufferTex, l_pixelCoords, vec4(colour, 1.0f));
}