#version 430 core

layout(local_size_x = 8, local_size_y = 4) in;

layout(rgba32f, binding = 0) uniform image2D o_framebufferTex;

layout(rgba32f, binding = 1) uniform image2D hitLocations;
layout(rgba32f, binding = 2) uniform image2D triangleNormals;
layout(rgba32f, binding = 3) uniform image2D texMatInfo;
layout(rgba32f, binding = 4) uniform image2D shadowBuffer;

struct Material
{
    vec3 albedo;
    float metallic;
    float roughness;
    float ambientOcclusion;
};

layout(std430, binding = 8) readonly buffer b_Materials
{
    Material materials[];
};

#define MAX_TEXTURES 10
layout(binding = 9) uniform sampler2D u_materialTextures[MAX_TEXTURES];

struct Camera { vec3 position; vec3 forward; vec3 right; vec3 up; };
uniform Camera u_camera;
struct Light
{
    vec3 points[4];
    vec3 colour;
    float intensity;
    float radius;
    bool twoSided;
};
#define MAX_LIGHTS 10
uniform Light u_lights[MAX_LIGHTS];
uniform int u_numLights;

const float PI = 3.14159265359;
// ----------------------------------------------------------------------------
float DistributionGGX(vec3 N, vec3 H, float roughness)
{
    float a = roughness*roughness;
    float a2 = a*a;
    float NdotH = max(dot(N, H), 0.0);
    float NdotH2 = NdotH*NdotH;

    float nom   = a2;
    float denom = (NdotH2 * (a2 - 1.0) + 1.0);
    denom = PI * denom * denom;

    return nom / denom;
}
// ----------------------------------------------------------------------------
float GeometrySchlickGGX(float NdotV, float roughness)
{
    float r = (roughness + 1.0);
    float k = (r*r) / 8.0;

    float nom   = NdotV;
    float denom = NdotV * (1.0 - k) + k;

    return nom / denom;
}
// ----------------------------------------------------------------------------
float GeometrySmith(vec3 N, vec3 V, vec3 L, float roughness)
{
    float NdotV = max(dot(N, V), 0.0);
    float NdotL = max(dot(N, L), 0.0);
    float ggx2 = GeometrySchlickGGX(NdotV, roughness);
    float ggx1 = GeometrySchlickGGX(NdotL, roughness);

    return ggx1 * ggx2;
}
// ----------------------------------------------------------------------------
vec3 fresnelSchlick(float cosTheta, vec3 F0)
{
    return F0 + (1.0 - F0) * pow(clamp(1.0 - cosTheta, 0.0, 1.0), 5.0);
}
// ----------------------------------------------------------------------------

void main()
{
    ivec2 l_pixelCoords = ivec2(gl_GlobalInvocationID.xy);

    vec3 l_position = imageLoad(hitLocations, l_pixelCoords).xyz;
    float l_distance = imageLoad(hitLocations, l_pixelCoords).w;
    vec2 l_texUVs = imageLoad(texMatInfo, l_pixelCoords).rg;

    if(l_distance < 0.01f)
    {
        imageStore(o_framebufferTex, l_pixelCoords, vec4(0.0, 0.1, 0.3, 1.0f));
        return;
    }

    imageStore(o_framebufferTex, l_pixelCoords, vec4(1.0, 0.0, 0.0, 1.0f));
    return;

    int l_texId = int(imageLoad(texMatInfo, l_pixelCoords).b);
    int l_matId = int(imageLoad(texMatInfo, l_pixelCoords).a);
    
    vec3 l_objectcolour = texture(u_materialTextures[l_texId], l_texUVs).rgb;

    Material l_mat = materials[l_matId];

    // Flip normal if it's facing away from the ray (backface)
    vec3 l_normal = normalize(imageLoad(triangleNormals, l_pixelCoords).rgb);
    vec3 V = normalize(u_camera.position - l_position);

    vec3 F0 = mix(vec3(0.04), l_mat.albedo, l_mat.metallic);
    vec3 Lo = vec3(0.0f);
    for(int i = 0; i < u_numLights; i++)
    {   
        vec3 l_lightDir = normalize(u_lights[i].points[0] - l_position);
        vec3 l_halfLength = normalize(V + l_lightDir);
        float l_distance = length(u_lights[i].points[0] - l_position);
        float l_attenuation = 1.0 / (l_distance * l_distance);
        vec3 l_radiance = u_lights[i].colour * u_lights[i].intensity * l_attenuation;

        // Cook-Torrance BRDF
        float NDF = DistributionGGX(l_normal, l_halfLength, l_mat.roughness);
        float G = GeometrySmith(l_normal, V, l_lightDir, l_mat.roughness);
        vec3 F = fresnelSchlick(clamp(dot(l_halfLength, V), 0.0, 1.0), F0);

        vec3 l_numerator = NDF * G * F;

        float NdotL = max(dot(l_normal, l_lightDir), 0.0);
        float l_denom = 4.0 * max(dot(l_normal, V), 0.0) * NdotL + 0.001;
        vec3 l_specular = l_numerator / l_denom;

        vec3 kS = F;

        vec3 kD = vec3(1.0) - kS;

        kD *= 1.0 - l_mat.metallic;

        Lo += ((kD * l_mat.albedo * l_objectcolour) / PI + l_specular) * l_radiance * NdotL;
    };
    
    // Add ambient lighting (always present, even in shadows)
    vec3 l_ambient = vec3(0.03) * l_objectcolour * l_mat.albedo * l_mat.ambientOcclusion;
    
    vec3 colour = l_ambient + Lo;

    // Gamma correction
    colour = pow(colour, vec3(1.0/2.2)) * imageLoad(shadowBuffer, l_pixelCoords).rgb;
    
    imageStore(o_framebufferTex, l_pixelCoords, vec4(colour, 1.0f));
}