#version 430 core

layout(local_size_x = 8, local_size_y = 4) in;
layout(rgba32f, binding = 0) uniform image2D o_framebufferTex;

layout(rgba32f, binding = 1) uniform image2D hitLocations;
layout(rgba32f, binding = 2) uniform image2D triangleNormals;

layout(rgba32f, binding = 4) uniform image2D shadowBuffer;


struct Triangle
{
    // Vertex positions
    vec3 a;
    vec3 b;
    vec3 c;
    vec3 normal;

    // UV Coordinates for each vertex
    vec2 uvA;
    vec2 uvB;
    vec2 uvC;

    int textureIndex;
    int materialIndex;
};

layout(std430, binding = 5) readonly buffer b_trianglesSSBO
{
    Triangle sceneTris[];
};


struct Node
{
    // Laid out like this for bit packing
    vec3 minBound;

    // Holds index of left node (if not leaf node) or first triangle (if leaf node)
    int leftFirst;
    vec3 maxBound;

    // Triangles in node (0 if not leaf node)
    int triangleCount;
};

layout(std430, binding = 6) readonly buffer b_bvhNodes
{
    Node bvhNodes[];
};

// Maps bvhNode.leftFirst indexes to indexes in sceneTris
layout(std430, binding = 7) readonly buffer b_bvhTriangleIndex
{
    int bvhTriIdxs[];
};

#define MAX_LIGHTS 10
struct Light
{
    vec3 points[4];
    vec3 colour;
    float intensity;
    float radius;
    bool twoSided;
};

uniform Light u_lights[MAX_LIGHTS];
uniform int u_numLights;

uniform int u_sampleCount;

uniform float u_time;

struct Ray  { vec3 origin; vec3 direction; };

struct RaycastResult {
    bool hit;
    float distance;
    vec3 position;
    vec3 normal;
    int triangleIndex;
};

const float PI = 3.14159265359;

// A "random" function I found in a stack overflow comment section
// Basically, the pattern between sequential values is too much to make
// to a person, so it may aswell be random
uint pcg_hash(uint seed)
{
  uint state = seed * 747796405u + 2891336453u;
  uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
  return (word >> 22u) ^ word;
}

// Used to advance the PCG state.
uint rand_pcg(inout uint rng_state)
{
  uint state = rng_state;
  rng_state = rng_state * 747796405u + 2891336453u;
  uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
  return (word >> 22u) ^ word;
}

// Advances the prng state and returns the corresponding random float.
float rand(uint state)
{
  uint x = rand_pcg(state);
  state = x;
  return float(x)*uintBitsToFloat(0x2f800000u);
}

RaycastResult TriangleIntersect(Ray _ray, Triangle _tri, int _index)
{
    RaycastResult result;
    result.hit = false;
    result.triangleIndex = _index;

    float l_ep = 0.0001;

    vec3 l_edgeAB = _tri.a;
    vec3 l_edgeAC = _tri.b; 
    vec3 l_edgeAP = _tri.c;

    vec3 edge1 = l_edgeAC - l_edgeAB;
    vec3 edge2 = l_edgeAP - l_edgeAB;
    vec3 ray_cross_edge2 = cross(_ray.direction, edge2);
    float det = dot(edge1, ray_cross_edge2);

    if(det > -l_ep && det < l_ep)
    {
        return result;
    }

    float inv_det = 1.0 / det;
    vec3 s = _ray.origin - l_edgeAB;
    float u = inv_det * dot(s, ray_cross_edge2);

    if(u < 0.0 || u > 1.0)
    {
        return result;
    }

    vec3 s_cross_e1 = cross(s, edge1);
    float v = inv_det * dot(_ray.direction, s_cross_e1);

    if(v < 0.0 || u + v > 1.0)
    {
        return result;
    }

    float t = inv_det * dot(edge2, s_cross_e1);

    if(t > l_ep)
    {
        result.hit = true;
        result.position = _ray.origin + _ray.direction * t;
        result.distance = t;
        result.normal = _tri.normal;
        return result;
    }

    return result;
}

bool IntersectAABB(inout Ray _ray, vec3 _minBound, vec3 _maxBound)
{
    float tmin = 0.0f;
    float tmax = 10000000.0f;

    for (int i = 0; i < 3; i++)
    {
        if (abs(_ray.direction[i]) < 0.0001f)
        {
            if (_ray.origin[i] < _minBound[i] || _ray.origin[i] > _maxBound[i])
                return false;
        }
        else
        {
            float ood = 1.0f / _ray.direction[i];
            float t1 = (_minBound[i] - _ray.origin[i]) * ood;
            float t2 = (_maxBound[i] - _ray.origin[i]) * ood;

            if (t1 > t2)
            {
                float temp = t1;
                t1 = t2;
                t2 = temp;
            }

            tmin = max(tmin, t1);
            tmax = min(tmax, t2);

            if (tmin > tmax)
            {
                return false;
            }
        }
    }

    return true;
}

// Shadow ray tracing (simplified version of TraverseBVH)
bool IsInShadow(vec3 _lightPos, vec3 _position, vec3 _normal, int _idx)
{
    Ray l_shadowRay;
    l_shadowRay.origin = _position + _normal * 0.001;
    l_shadowRay.direction = normalize(_lightPos - _position);
    
    float l_lightDistance = length(_lightPos - _position);
    
    int l_indexStack[64];
    int l_top = 0;
    l_indexStack[l_top] = 0;

    Node l_node = bvhNodes[l_indexStack[l_top]];
    l_top++;

    do
    {
        if(IntersectAABB(l_shadowRay, l_node.minBound, l_node.maxBound))
        {
            if(l_node.triangleCount > 0)
            {
                for(int i = 0; i < l_node.triangleCount; i++)
                {
                    // Skip the same triangle
                    if(bvhTriIdxs[l_node.leftFirst + i] == _idx)
                    {
                        continue;
                    }

                    RaycastResult l_shadowHit = TriangleIntersect(l_shadowRay, sceneTris[bvhTriIdxs[l_node.leftFirst + i]], bvhTriIdxs[l_node.leftFirst + i]);
                    
                    // More than a minimum value to ignore close sceneTris
                    if(l_shadowHit.hit && l_shadowHit.distance < l_lightDistance && l_shadowHit.distance > 0.01f)
                    {
                        return true;
                    }
                }
            }
            else
            {
                l_indexStack[l_top] = l_node.leftFirst;
                l_top++;
                l_indexStack[l_top] = l_node.leftFirst + 1;
                l_top++;
            }
        }

        l_top--;
        l_node = bvhNodes[l_indexStack[l_top]];
    } while(l_top > -1);

    return false;
}

void main() 
{
    ivec2 l_pixelCoords = ivec2(gl_GlobalInvocationID.xy);
    
    vec3 l_position = imageLoad(hitLocations, l_pixelCoords).rgb;
    vec4 l_normalBVal = imageLoad(triangleNormals, l_pixelCoords);
    vec3 l_normal = l_normalBVal.rgb;
    int l_triIndex = int(l_normalBVal.a);
    
    if (length(l_position) < 0.001) {
        imageStore(shadowBuffer, l_pixelCoords, vec4(1.0)); // No shadow for background
        return;
    }
    
    vec3 l_totalLight = imageLoad(shadowBuffer, l_pixelCoords).xyz;
    
    // Check shadows for each light
    for(int i = 0; i < u_numLights; i++)
    {
        vec3 l_incomingLight = vec3(0.0f);
        for(int j = 0; j < u_sampleCount; j++)
        {
            vec3 l_randomPoint = normalize(vec3(rand(gl_GlobalInvocationID.x),
                                                rand(uint(u_time)),
                                                rand(gl_GlobalInvocationID.y)));

            // Translate point to surface of sphere
            l_randomPoint *= u_lights[i].radius;
            l_randomPoint += u_lights[i].points[0];
            
            vec3 lightDir = normalize(l_randomPoint - l_position);
            float lightDistance = length(l_randomPoint - l_position);
            float l_cosTheta = dot(lightDir, l_normal);

            // https://www.physicsforums.com/threads/luminance-of-a-lambertian-sphere-formula.449703/
            // Scales light intensity with inverse square
            vec3 l_lightIntensity = l_cosTheta * 
                                    u_lights[i].colour * 
                                    u_lights[i].intensity * 
                                    u_lights[i].radius * u_lights[i].radius *
                                    PI * 4 / (lightDistance * lightDistance);


            // Point is behind the light source or occluded
            if (l_cosTheta <= 0 || IsInShadow(l_randomPoint, l_position, l_normal, l_triIndex))
            {
                continue;
            }
            
            l_incomingLight += l_lightIntensity;
        }

        l_incomingLight /= u_sampleCount;
        l_totalLight += l_incomingLight;
    }
    
    imageStore(shadowBuffer, l_pixelCoords, vec4(l_totalLight, 1.0f));
}