#version 430 core

layout(local_size_x = 8, local_size_y = 4) in;

layout(rgba32f, binding = 0) uniform image2D o_framebufferTex;
layout(rgba32f, binding = 1) uniform image2D hitLocations;

struct Camera { vec3 position; vec3 forward; vec3 right; vec3 up; float fov; };
uniform Camera u_camera;

struct Light
{
    vec3 position;
    float intensity;
    vec3 colour;
    float radius;
};

layout(std430, binding = 12) readonly buffer b_LightData
{
    Light u_lights[];
};

uniform vec2 u_resolution;

struct Ray  { vec3 origin; vec3 direction; };

struct RaycastResult {
    bool hit;
    float distance;
    int lightIdx;
};

float IntersectSphere(Ray _ray, vec3 _spherePos, float _radius)
{
    vec3 oc = _ray.origin - _spherePos;
    float a = dot(_ray.direction, _ray.direction);
    float b = 2.0 * dot(oc, _ray.direction);
    float c = dot(oc, oc) - _radius * _radius;
    
    float l_discriminant = b * b - 4.0 * a * c;
    
    if (l_discriminant < 0.0)
    {
        return 1e30f;
    }
    
    float sqrtDisc = sqrt(l_discriminant);
    float l_hitLocation1 = (-b - sqrtDisc) / (2.0 * a);
    float l_hitLocation2 = (-b + sqrtDisc) / (2.0 * a);
    
    float l_distance = (l_hitLocation1 > 0.0) ? l_hitLocation1 : l_hitLocation2;
    if (l_distance <= 0.0)
    {
        return 1e30f;
    }
    
    return l_distance;
}

void main()
{
    ivec2 l_pixelCoords = ivec2(gl_GlobalInvocationID.xy);

    vec2 l_normalizedScreenCoords = vec2(((float(l_pixelCoords.x) / u_resolution.x) - 0.5) * 2.0,
                                         ((float(l_pixelCoords.y) / u_resolution.y) - 0.5) * 2.0);

    // Calculate aspect ratio
    float aspect = u_resolution.x / u_resolution.y;

    float tanHalfFov = tan(u_camera.fov * 0.5);
    
    // Scale the horizontal component by aspect ratio and FOV
    float horizontalScale = tanHalfFov * aspect;
    float verticalScale = tanHalfFov;

    vec3 l_rayDir = normalize(
        u_camera.forward + 
        l_normalizedScreenCoords.x * u_camera.right * horizontalScale + 
        l_normalizedScreenCoords.y * u_camera.up * verticalScale
    );
    
    Ray l_ray;
    l_ray.origin = u_camera.position;
    l_ray.direction = l_rayDir;

    int l_hitLightIdx = -1;
    float l_closestHitDistance = 1e30f;
    float l_currentDistance = 1e30f;
    vec3 l_normal = vec3(0.0f);

    int l_lightCount = u_lights.length();

    for(int i = 0; i < l_lightCount; i++)
    {
        l_currentDistance = IntersectSphere(l_ray, u_lights[i].position, u_lights[i].radius);

        if(l_currentDistance < l_closestHitDistance)
        {
            l_closestHitDistance = l_currentDistance;

            l_normal = normalize((l_ray.origin + l_ray.direction * l_closestHitDistance) - u_lights[i].position);

            l_hitLightIdx = i;
        }
    }

    if(l_hitLightIdx < 0)
    {
        return;
    }


    float l_closestObjHit = imageLoad(hitLocations, l_pixelCoords).w;

    if(l_closestHitDistance < l_closestObjHit)
    {
        float NdotD = -dot(l_normal, l_ray.direction);
        vec3 l_colourToWrite = u_lights[l_hitLightIdx].colour * NdotD;

        imageStore(o_framebufferTex, l_pixelCoords, vec4(l_colourToWrite, 1.0f));
    }
}