#version 430 core

layout(local_size_x = 8, local_size_y = 4) in;

layout(rgba32f, binding = 0) uniform image2D o_framebufferTex;

layout(rgba32f, binding = 1) uniform image2D hitLocations;
layout(rgba32f, binding = 2) uniform image2D triangleNormals;
layout(rgba32f, binding = 3) uniform image2D texMatInfo;
layout(rgba32f, binding = 4) uniform image2D shadowBuffer;

struct Material
{
    vec3 albedo;
    float metallic;
    float roughness;
    float ambientOcclusion;
};

layout(std430, binding = 8) readonly buffer b_Materials
{
    Material materials[];
};

#define MAX_TEXTURES 10
layout(binding = 9) uniform sampler2D u_materialTextures[MAX_TEXTURES];

uniform vec3 u_cameraPos;
struct Light
{
    vec3 position;
    vec3 colour;
    float intensity;

    // Values for sphere light
    float radius;

    // Values for Square area light
    vec3 cornerA;
    vec3 cornerB;
};

#define MAX_LIGHTS 10
uniform Light u_lights[MAX_LIGHTS];
uniform int u_lightCount;

void main()
{
    ivec2 l_pixelCoords = ivec2(gl_GlobalInvocationID.xy);

    vec3 l_position = imageLoad(hitLocations, l_pixelCoords).xyz;
    float l_posDistance = imageLoad(hitLocations, l_pixelCoords).w;
    vec2 l_texUVs = imageLoad(texMatInfo, l_pixelCoords).rg;

    // No light or object hit, so background
    if(l_posDistance == 1e30f)
    {
        imageStore(o_framebufferTex, l_pixelCoords, vec4(0.0, 0.1, 0.3, 1.0));
        return;
    }

    int l_texId = int(imageLoad(texMatInfo, l_pixelCoords).b);
    
    vec3 l_texColour = vec3(1.0);

    if(l_texId > -1)
    {
        l_texColour = texture(u_materialTextures[l_texId], l_texUVs).rgb;
    }

    vec3 l_normal = normalize(imageLoad(triangleNormals, l_pixelCoords).rgb);
    vec3 V = normalize(u_cameraPos - l_position);

    vec3 l_light = vec3(0.0f);

    for(int i = 0; i < u_lightCount; i++)
    {
        vec3 l_lightPosition = vec3(0.0);
        if(u_lights[i].radius > 0.0f)
        {
            l_lightPosition = u_lights[i].position;
        }
        else
        {
            l_lightPosition = u_lights[i].position
                              + 0.5 * (u_lights[i].cornerA - u_lights[i].position)
                              + 0.5 * (u_lights[i].cornerB - u_lights[i].position);
        }

        vec3 l_lightDir = normalize(l_lightPosition - l_position);
        float NdotL = max(dot(l_normal, l_lightDir), 0.0f);
        float l_distance = length(l_lightPosition - l_position);
        float l_attenuation = 1.0 / (1.0 + 0.1 * l_distance * l_distance);
        vec3 l_radiance = u_lights[i].colour * u_lights[i].intensity * l_attenuation;

        l_light += l_radiance * NdotL;
    }
    
    // Add ambient lighting (always present, even in shadows)
    vec3 l_ambient = vec3(0.03) * l_texColour;
    
    vec3 l_shadow = imageLoad(shadowBuffer, l_pixelCoords).xyz;

    vec3 colour = (l_ambient + l_light) * l_shadow * l_texColour;

    // Gamma correction
    colour = pow(colour, vec3(1.0/2.2));
    
    imageStore(o_framebufferTex, l_pixelCoords, vec4(colour, 1.0f));
}