#version 430 core

layout(local_size_x = 8, local_size_y = 4) in;

layout(rgba32f, binding = 0) uniform image2D o_framebufferTex;

layout(rgba32f, binding = 1) uniform image2D hitLocations;
layout(rgba32f, binding = 2) uniform image2D triangleNormals;
layout(rgba32f, binding = 3) uniform image2D texMatInfo;
layout(rgba32f, binding = 4) uniform image2D shadowBuffer;

struct Material
{
    vec3 albedo;
    float metallic;
    float roughness;
    float ambientOcclusion;
};

layout(std430, binding = 10) readonly buffer b_Materials
{
    Material materials[];
};

uniform sampler2D u_materialTextures[32];

struct Light
{
    vec3 position;
    float intensity;
    vec3 colour;
    float radius;
};

layout(std430, binding = 12) readonly buffer b_LightData
{
    Light u_lights[];
};

struct Camera
{
    vec3 position;
};

uniform Camera u_camera;

const float PI = 3.14159265359;
// ----------------------------------------------------------------------------
float DistributionGGX(vec3 N, vec3 H, float roughness)
{
    float a = roughness*roughness;
    float a2 = a*a;
    float NdotH = max(dot(N, H), 0.0);
    float NdotH2 = NdotH*NdotH;

    float nom   = a2;
    float denom = (NdotH2 * (a2 - 1.0) + 1.0);
    denom = PI * denom * denom;

    return nom / denom;
}
// ----------------------------------------------------------------------------
float GeometrySchlickGGX(float NdotV, float roughness)
{
    float r = (roughness + 1.0);
    float k = (r*r) / 8.0;

    float nom   = NdotV;
    float denom = NdotV * (1.0 - k) + k;

    return nom / denom;
}
// ----------------------------------------------------------------------------
float GeometrySmith(vec3 N, vec3 V, vec3 L, float roughness)
{
    float NdotV = max(dot(N, V), 0.0);
    float NdotL = max(dot(N, L), 0.0);
    float ggx2 = GeometrySchlickGGX(NdotV, roughness);
    float ggx1 = GeometrySchlickGGX(NdotL, roughness);

    return ggx1 * ggx2;
}
// ----------------------------------------------------------------------------
vec3 fresnelSchlick(float cosTheta, vec3 F0)
{
    return F0 + (1.0 - F0) * pow(clamp(1.0 - cosTheta, 0.0, 1.0), 5.0);
}
// ----------------------------------------------------------------------------

void main()
{
    ivec2 l_pixelCoords = ivec2(gl_GlobalInvocationID.xy);

    vec3 l_position = imageLoad(hitLocations, l_pixelCoords).xyz;
    float l_posDistance = imageLoad(hitLocations, l_pixelCoords).w;
    vec2 l_texUVs = imageLoad(texMatInfo, l_pixelCoords).rg;

    // No light or object hit, so background
    if(l_posDistance == 1e30f)
    {
        imageStore(o_framebufferTex, l_pixelCoords, vec4(0.0, 0.1, 0.3, 1.0));
        return;
    }

    int l_texId = int(imageLoad(texMatInfo, l_pixelCoords).b);
    int l_matId = int(imageLoad(texMatInfo, l_pixelCoords).a);
    
    vec3 l_texColour = vec3(1.0);

    if(l_texId > -1)
    {
        l_texColour = texture(u_materialTextures[l_texId], l_texUVs).rgb;
    }

    Material l_mat;

    if(l_matId > -1)
    {
        l_mat = materials[l_matId];
    }
    else
    {
        l_mat.albedo = vec3(1.0);
        l_mat.metallic = 1.0;
        l_mat.roughness = 0.0;
        l_mat.ambientOcclusion = 1.0;
    }

    vec3 l_normal = normalize(imageLoad(triangleNormals, l_pixelCoords).rgb);
    vec3 V = normalize(u_camera.position - l_position);

    vec3 F0 = mix(vec3(0.04), l_mat.albedo, l_mat.metallic);
    vec3 Lo = vec3(0.0f);

    int l_lightCount = u_lights.length();
    for(int i = 0; i < l_lightCount; i++)
    {
        vec3 l_lightPosition = u_lights[i].position;

        vec3 l_lightDir = normalize(l_lightPosition - l_position);
        vec3 l_halfLength = normalize(V + l_lightDir);
        float l_distance = length(l_lightPosition - l_position);
        float l_attenuation = 1.0 / (1.0 + 0.1 * l_distance * l_distance);
        vec3 l_radiance = u_lights[i].colour * u_lights[i].intensity * l_attenuation;

        // Cook-Torrance BRDF
        float NDF = DistributionGGX(l_normal, l_halfLength, l_mat.roughness);
        float G = GeometrySmith(l_normal, V, l_lightDir, l_mat.roughness);
        vec3 F = fresnelSchlick(clamp(dot(l_halfLength, V), 0.0, 1.0), F0);

        vec3 l_numerator = NDF * G * F;

        float NdotL = max(dot(l_normal, l_lightDir), 0.0f);
        float l_denom = 4.0 * max(dot(l_normal, V), 0.0) * NdotL + 0.001;
        vec3 l_specular = l_numerator / l_denom;

        vec3 kS = F;

        vec3 kD = vec3(1.0) - kS;

        kD *= 1.0 - l_mat.metallic;

        Lo += ((kD * l_mat.albedo) / PI + l_specular) * l_radiance * NdotL;
    }
    
    // Add ambient lighting (always present, even in shadows)
    vec3 l_ambient = vec3(0.03) * l_mat.albedo * l_mat.ambientOcclusion;
    
    vec3 l_shadow = imageLoad(shadowBuffer, l_pixelCoords).xyz;

    vec3 colour = (l_ambient + Lo) * l_shadow * l_texColour;

    // Gamma correction
    colour = pow(colour, vec3(1.0/2.2));
    
    imageStore(o_framebufferTex, l_pixelCoords, vec4(colour, 1.0f));
}